@IFC
@version2
@industry-practice
Feature: IFC431 - Entities in scope for IFC 4X3 Alignment-basedView MVD

The rule verifies that IFC models using schema version 4.3 and declaring the Alignment-basedView Model View Definition (MVD)
do not export any entities that are outside the scope of this MVD.

  Scenario Outline: Check for in-scope entities - IFC4.3 Alignment-basedView

    Given A model with Schema 'IFC4.3'
    Given A model with Model View Definition 'Alignment-basedView'
    Given An IFC model

    Then There must be less than 1 instance(s) of .<Entity>. ^excluding subtypes^

    Examples:
      | Entity                                       |
      | IfcAdvancedBrep                              |
      | IfcAdvancedBrepWithVoids                     |
      | IfcAdvancedFace                              |
      | IfcApproval                                  |
      | IfcApprovalRelationship                      |
      | IfcArbitraryOpenProfileDef                   |
      | IfcAsymmetricIShapeProfileDef                |
      | IfcBlobTexture                               |
      | IfcBlock                                     |
      | IfcBooleanClippingResult                     |
      | IfcBooleanResult                             |
      | IfcBoundaryCondition                         |
      | IfcBoundaryCurve                             |
      | IfcBoundaryEdgeCondition                     |
      | IfcBoundaryFaceCondition                     |
      | IfcBoundaryNodeCondition                     |
      | IfcBoundaryNodeConditionWarping              |
      | IfcBoundedSurface                            |
      | IfcBoxedHalfSpace                            |
      | IfcBSplineCurve                              |
      | IfcBSplineCurveWithKnots                     |
      | IfcBSplineSurface                            |
      | IfcBSplineSurfaceWithKnots                   |
      | IfcCenterLineProfileDef                      |
      | IfcCircleHollowProfileDef                    |
      | IfcCircleProfileDef                          |
      | IfcComplexProperty                           |
      | IfcComplexPropertyTemplate                   |
      | IfcCompositeCurveOnSurface                   |
      | IfcCompositeCurveSegment                     |
      | IfcConnectedFaceSet                          |
      | IfcConnectionCurveGeometry                   |
      | IfcConnectionPointEccentricity               |
      | IfcConnectionPointGeometry                   |
      | IfcConnectionSurfaceGeometry                 |
      | IfcConnectionVolumeGeometry                  |
      | IfcConstraint                                |
      | IfcContextDependentUnit                      |
      | IfcCostItem                                  |
      | IfcCostSchedule                              |
      | IfcCsgPrimitive3D                            |
      | IfcCsgSolid                                  |
      | IfcCShapeProfileDef                          |
      | IfcCurrencyRelationship                      |
      | IfcCurveBoundedPlane                         |
      | IfcCurveBoundedSurface                       |
      | IfcCurveStyleFontAndScaling                  |
      | IfcCylindricalSurface                        |
      | IfcDerivedProfileDef                         |
      | IfcDirectrixCurveSweptAreaSolid              |
      | IfcDirectrixDerivedReferenceSweptAreaSolid   |
      | IfcDistributionCircuit                       |
      | IfcDocumentInformationRelationship           |
      | IfcDoorLiningProperties                      |
      | IfcDoorPanelProperties                       |
      | IfcDraughtingPreDefinedColour                |
      | IfcDraughtingPreDefinedCurveFont             |
      | IfcEdge                                      |
      | IfcEdgeCurve                                 |
      | IfcEdgeLoop                                  |
      | IfcElementarySurface                         |
      | IfcEllipse                                   |
      | IfcEllipseProfileDef                         |
      | IfcExternallyDefinedHatchStyle               |
      | IfcExternallyDefinedSurfaceStyle             |
      | IfcExternallyDefinedTextFont                 |
      | IfcExternalReferenceRelationship             |
      | IfcExtrudedAreaSolid                         |
      | IfcExtrudedAreaSolidTapered                  |
      | IfcFace                                      |
      | IfcFaceBasedSurfaceModel                     |
      | IfcFaceBound                                 |
      | IfcFaceOuterBound                            |
      | IfcFaceSurface                               |
      | IfcFacetedBrepWithVoids                      |
      | IfcFailureConnectionCondition                |
      | IfcFillAreaStyleTiles                        |
      | IfcFixedReferenceSweptAreaSolid              |
      | IfcGeomodel                                  |
      | IfcGeoslice                                  |
      | IfcGridPlacement                             |
      | IfcHalfSpaceSolid                            |
      | IfcIndexedPolygonalTextureMap                |
      | IfcIntersectionCurve                         |
      | IfcIrregularTimeSeries                       |
      | IfcIrregularTimeSeriesValue                  |
      | IfcIShapeProfileDef                          |
      | IfcLagTime                                   |
      | IfcLibraryInformation                        |
      | IfcLibraryReference                          |
      | IfcLightDistributionData                     |
      | IfcLightIntensityDistribution                |
      | IfcLightSource                               |
      | IfcLightSourceAmbient                        |
      | IfcLightSourceDirectional                    |
      | IfcLightSourceGoniometric                    |
      | IfcLightSourcePositional                     |
      | IfcLightSourceSpot                           |
      | IfcLoop                                      |
      | IfcLShapeProfileDef                          |
      | IfcMaterialClassificationRelationship        |
      | IfcMaterialDefinitionRepresentation          |
      | IfcMaterialLayerSetUsage                     |
      | IfcMaterialLayerWithOffsets                  |
      | IfcMaterialList                              |
      | IfcMaterialProfileSetUsage                   |
      | IfcMaterialProfileSetUsageTapering           |
      | IfcMaterialProfileWithOffsets                |
      | IfcMaterialRelationship                      |
      | IfcMaterialUsageDefinition                   |
      | IfcMapConversionScaled
      | IfcMetric                                    |
      | IfcMirroredProfileDef                        |
      | IfcObjective                                 |
      | IfcOccupant                                  |
      | IfcOffsetCurve                               |
      | IfcOffsetCurve2D                             |
      | IfcOffsetCurve3D                             |
      | IfcOffsetCurveByDistances                    |
      | IfcOpenShell                                 |
      | IfcOrganizationRelationship                  |
      | IfcOrientedEdge                              |
      | IfcOuterBoundaryCurve                        |
      | IfcParameterizedProfileDef                   |
      | IfcPath                                      |
      | IfcPcurve                                    |
      | IfcPerformanceHistory                        |
      | IfcPermeableCoveringProperties               |
      | IfcPhysicalComplexQuantity                   |
      | IfcPixelTexture                              |
      | IfcPlanarBox                                 |
      | IfcPlanarExtent                              |
      | IfcPlane                                     |
      | IfcPointOnCurve                              |
      | IfcPointOnSurface                            |
      | IfcPolygonalBoundedHalfSpace                 |
      | IfcPolyLoop                                  |
      | IfcPreDefinedColour                          |
      | IfcPreDefinedCurveFont                       |
      | IfcPreDefinedProperties                      |
      | IfcPreDefinedPropertySet                     |
      | IfcPresentationLayerWithStyle                |
      | IfcProfileProperties                         |
      | IfcPropertyDependencyRelationship            |
      | IfcPropertyReferenceValue                    |
      | IfcQuantityNumber                            |
      | IfcRationalBSplineCurveWithKnots             |
      | IfcRationalBSplineSurfaceWithKnots           |
      | IfcRectangleHollowProfileDef                 |
      | IfcRectangleProfileDef                       |
      | IfcRectangularPyramid                        |
      | IfcRectangularTrimmedSurface                 |
      | IfcRecurrencePattern                         |
      | IfcReference                                 |
      | IfcRegularTimeSeries                         |
      | IfcReinforcementBarProperties                |
      | IfcReinforcementDefinitionProperties         |
      | IfcRelAdheresToElement                       |
      | IfcRelAssignsToActor                         |
      | IfcRelAssignsToControl                       |
      | IfcRelAssignsToGroupByFactor                 |
      | IfcRelAssignsToProcess                       |
      | IfcRelAssignsToProduct                       |
      | IfcRelAssignsToResource                      |
      | IfcRelAssociatesApproval                     |
      | IfcRelAssociatesConstraint                   |
      | IfcRelAssociatesLibrary                      |
      | IfcRelAssociatesProfileDef                   |
      | IfcRelConnectsElements                       |
      | IfcRelConnectsPathElements                   |
      | IfcRelConnectsPortToElement                  |
      | IfcRelConnectsStructuralActivity             |
      | IfcRelConnectsStructuralMember               |
      | IfcRelConnectsWithEccentricity               |
      | IfcRelConnectsWithRealizingElements          |
      | IfcRelCoversSpaces                           |
      | IfcRelDefinesByObject                        |
      | IfcRelDefinesByTemplate                      |
      | IfcRelFlowControlElements                    |
      | IfcRelProjectsElement                        |
      | IfcRelSequence                               |
      | IfcRelServicesBuildings                      |
      | IfcRelSpaceBoundary                          |
      | IfcRelSpaceBoundary1stLevel                  |
      | IfcRelSpaceBoundary2ndLevel                  |
      | IfcReparametrisedCompositeCurveSegment       |
      | IfcResourceApprovalRelationship              |
      | IfcResourceConstraintRelationship            |
      | IfcResourceLevelRelationship                 |
      | IfcRevolvedAreaSolid                         |
      | IfcRevolvedAreaSolidTapered                  |
      | IfcRightCircularCone                         |
      | IfcRightCircularCylinder                     |
      | IfcRoundedRectangleProfileDef                |
      | IfcSchedulingTime                            |
      | IfcSeamCurve                                 |
      | IfcSectionedSpine                            |
      | IfcSectionProperties                         |
      | IfcSectionReinforcementProperties            |
      | IfcShapeAspect                               |
      | IfcShellBasedSurfaceModel                    |
      | IfcSimplePropertyTemplate                    |
      | IfcSlippageConnectionCondition               |
      | IfcSphere                                    |
      | IfcSphericalSurface                          |
      | IfcStructuralAction                          |
      | IfcStructuralActivity                        |
      | IfcStructuralConnection                      |
      | IfcStructuralConnectionCondition             |
      | IfcStructuralCurveAction                     |
      | IfcStructuralCurveConnection                 |
      | IfcStructuralCurveMember                     |
      | IfcStructuralCurveMemberVarying              |
      | IfcStructuralCurveReaction                   |
      | IfcStructuralLinearAction                    |
      | IfcStructuralLoad                            |
      | IfcStructuralLoadConfiguration               |
      | IfcStructuralLoadLinearForce                 |
      | IfcStructuralLoadOrResult                    |
      | IfcStructuralLoadPlanarForce                 |
      | IfcStructuralLoadSingleDisplacement          |
      | IfcStructuralLoadSingleDisplacementDistortion|
      | IfcStructuralLoadSingleForce                 |
      | IfcStructuralLoadSingleForceWarping          |
      | IfcStructuralLoadStatic                      |
      | IfcStructuralLoadTemperature                 |
      | IfcStructuralPlanarAction                    |
      | IfcStructuralPointAction                     |
      | IfcStructuralPointConnection                 |
      | IfcStructuralPointReaction                   |
      | IfcStructuralReaction                        |
      | IfcStructuralSurfaceAction                   |
      | IfcStructuralSurfaceConnection               |
      | IfcStructuralSurfaceReaction                 |
      | IfcStyledRepresentation                      |
      | IfcStyleModel                                |
      | IfcSubedge                                   |
      | IfcSurfaceCurve                              |
      | IfcSurfaceCurveSweptAreaSolid                |
      | IfcSurfaceOfLinearExtrusion                  |
      | IfcSurfaceOfRevolution                       |
      | IfcSurfaceReinforcementArea                  |
      | IfcSurfaceStyleLighting                      |
      | IfcSurfaceStyleRefraction                    |
      | IfcSurfaceStyleWithTextures                  |
      | IfcSweptDiskSolidPolygonal                   |
      | IfcSweptSurface                              |
      | IfcTable                                     |
      | IfcTableColumn                               |
      | IfcTableRow                                  |
      | IfcTaskTimeRecurring                         |
      | IfcTextLiteralWithExtent                     |
      | IfcTextureCoordinateGenerator                |
      | IfcTextureCoordinateIndices                  |
      | IfcTextureCoordinateIndicesWithVoids         |
      | IfcTextureMap                                |
      | IfcTextureVertex                             |
      | IfcTimePeriod                                |
      | IfcTimeSeries                                |
      | IfcTimeSeriesValue                           |
      | IfcTopologicalRepresentationItem             |
      | IfcTopologyRepresentation                    |
      | IfcToroidalSurface                           |
      | IfcTrapeziumProfileDef                       |
      | IfcTriangulatedIrregularNetwork              |
      | IfcTrimmedCurve                              |
      | IfcTShapeProfileDef                          |
      | IfcUShapeProfileDef                          |
      | IfcVertex                                    |
      | IfcVertexLoop                                |
      | IfcVertexPoint                               |
      | IfcVirtualGridIntersection                   |
      | IfcWallStandardCase                          |
      | IfcWindowLiningProperties                    |
      | IfcWindowPanelProperties                     |
      | IfcWorkCalendar                              |
      | IfcWorkPlan                                  |
      | IfcWorkSchedule                              |
      | IfcWorkTime                                  |
      | IfcZShapeProfileDef                          |
