name: Dispatch

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:

  dispatch:

    name: dispatch to validate
    runs-on: ubuntu-latest
      
    steps:
    
      - run: ${{ tojson(github.event) }}
        shell: cat {0}
        
      - run: |
          curl -H "Authorization: token ${{ secrets.VALIDATE_REPO_GH_TOKEN }} " \
          -H 'Accept: application/vnd.github.everest-preview+json' "${{ vars.VALIDATE_REPO_DISPATCH_URL }}" \
          -d '{ "event_type": "submodule_dispatch", "client_payload": { "owner": "${{ github.event.repository.owner.login }}", "repo": "${{ github.event.repository.name }}", "branch": "${{ github.ref_name }}" } }'
